PSMDB-1033 Implement MONGODB-AWS SASL mechanism
percona/percona-server-mongodb pull request #1000
Opened 2023-02-20 17:56 UTC by igorsol

2023-02-21 12:37 UTC, ktrushin requested changes

2023-02-21 20:03 UTC, igorsol commented on src/mongo/db/auth/external/awsiam_server_mechanism.cpp
> +}
accepted

2023-02-21 20:03 UTC, igorsol commented on src/mongo/db/auth/external/awsiam_server_mechanism.h
> +    void _parseStsResponse(StringData body);
fixed

2023-02-21 20:05 UTC, igorsol commented on src/mongo/db/auth/external/awsiam_server_mechanism.h
> +    void _parseStsResponse(StringData body);
by the way this header is only included in the corresponding *.cpp file

2023-02-21 20:05 UTC, igorsol commented on src/mongo/db/auth/external/awsiam_server_mechanism.h
> +    std::int32_t _gs2_cb_flag = 0;
fixed

2023-02-22 07:23 UTC, ktrushin approved these changes
Looks good

2023-02-22 09:41 UTC, merged